const INCREMENT_BREAK = 'INCREMENT_BREAK';
const DECREMENT_BREAK = 'DECREMENT_BREAK';
const INCREMENT_SESSION = 'INCREMENT_SESSION';
const DECREMENT_SESSION = 'DECREMENT_SESSION';
const START = 'START';
const STOP = 'STOP';
const RESET = 'RESET';

export default {
    INCREMENT_BREAK,
    DECREMENT_BREAK,
    INCREMENT_SESSION,
    DECREMENT_SESSION,
    START,
    STOP,
    RESET
};