const INCREMENT_BREAK = 'INCREMENT_BREAK';
const DECREMENT_BREAK = 'DECREMENT_BREAK';
const INCREMENT_SESSION = 'INCREMENT_SESSION';
const DECREMENT_SESSION = 'DECREMENT_SESSION';
const STOP = 'STOP';
const RESET = 'RESET';
const TICK = 'TICK';
const START_BREAK = 'START_BREAK';
const START_SESSION = 'START_SESSION';
const INITIAL_START = 'INITIAL_START';
const PLAY_AUDIO = 'PLAY_AUDIO';
const UPDATE_TOTAL_TIME = 'UPDATE_TOTAL_TIME';

export default {
    INCREMENT_BREAK,
    DECREMENT_BREAK,
    INCREMENT_SESSION,
    DECREMENT_SESSION,
    STOP,
    RESET,
    TICK,
    START_BREAK,
    START_SESSION,
    INITIAL_START,
    PLAY_AUDIO,
    UPDATE_TOTAL_TIME
};